### PR TITLE
create initial version of NDText component

### PR DESCRIPTION
**Pull request by jooaodanieel**
Co-authored-by: João Daniel <jotaf.daniel@gmail.com>
Co-authored-by: Luiz Carlos <luizcarlosdk@hotmail.com>
Co-authored-by: Marilia Dicezare <mariliatd@gmail.com>

### CODE REVIEW

**Comment by jooaodanieel** [comment]
Falta captar o evento `empty` no BulletList

**Comment by jooaodanieel** [comment]
Is this PR really ready for review? As I remember, when I added the `wontfix` tag, was because we decided to drop this approach. Did something change? If so, I'll take a look then :)

---
c.c. @luizcarlosdk

**Comment by luizcarlosdk** [comment]
> Is this PR really ready for review? As I remember, when I added the `wontfix` tag, was because we decided to drop this approach. Did something change? If so, I'll take a look then :)
> 
> c.c. @luizcarlosdk

I guess the wontfix were add cause there was a feature missing regarding empty in bulletlist, and this feature is what a solved now

**Comment by jooaodanieel** [comment]
> > Is this PR really ready for review? As I remember, when I added the `wontfix` tag, was because we decided to drop this approach. Did something change? If so, I'll take a look then :)
> > c.c. @luizcarlosdk
> 
> I guess the wontfix were add cause there was a feature missing regarding empty in bulletlist, and this feature is what a solved now

As I'm the one who opened this PR, GitHub isn't accepting my review.
I would approve hehehe even though I'm not the fondest of this solution -- but it's better than no solution, hence my acceptance!

Let's be agile in this sense: let's merge it, take feedback and improve this feature if needed.

**Pull request merged**
